### ISSUE TITLE
HTML CSS Vyhledávač

### ISSUE THREAD

**Issue by KrystofCavo23** [Stredni-skola-managementu-a-grafiky/UP3AI#41] opened 2022-05-02 10:44 UTC
HTML:
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="search-bar">
        <form action="">
            <input type="text", placeholder="Vyhledávač", name="q" >
            <button type="submit"><img src="search.png", class="ikona">,</button>
        
        </form>
    </div>
    
</body>
</html>

CSS:
*{
    margin: 0px;
    padding: 0px;

}

.search-bar{
    width: 100%;
    min-height: 100vh;
    padding: 5%;
    display: flex; 
    align-items: center;
    justify-content: center;
    

}

.ikona{
    width: 30px;
}
.search-bar input{
    display: flex;
    width: 300px;
    margin-bottom: 20px;
    border-radius: 50px;
    height: 50px;
    padding-left: 30px;

}

.search-bar button{
    display: flex;
    margin-left: 250px;
    margin-top: -65px;
    border: none;
    background: none;

}

**Comment by Onderko** [comment] 2022-05-02 10:44
děkuji kryštofe :)

**Comment by KrystofCavo23** [comment] 2022-05-02 10:45
<div class="search-bar">
        <form action="">
            <input type="text", placeholder="Vyhledávač", name="q" >
            <button type="submit"><img src="search.png", class="ikona">,</button>

**Comment by kubaran11** [comment] 2022-05-02 11:40
duplicate of #8

**Closed** 2022-05-02 12:04 UTC
Labels: frontend
